CREATE TABLE PRODUCTOS3 (
  CODIGOARTICULO VARCHAR(4),
  SECCION VARCHAR(11),
  NOMBREARTICULO VARCHAR(20)
);

INSERT INTO PRODUCTOS3 (CODIGOARTICULO, SECCION, NOMBREARTICULO) VALUES ('1','DEPORTES','PELOTA'), ('2','VIDEOJUEGOS', 'PS4');