CREATE DATABASE IF NOT EXISTS HERMOSILLOTODAY;
USE HERMOSILLOTODAY;

CREATE TABLE IF NOT EXISTS NEWS(
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  HEAD_BODY VARCHAR (255) NOT NULL,
  BODY TEXT NOT NULL,
  IMAGE VARCHAR(255),
  AUTHOR VARCHAR (255),
  CATEGORY ENUM('DEPORTES','INTERNACIONAL','ENTRETENIMIENTO', 'ESPECTACULOS','TECNOLOGIA','NACIONAL','ESTATAL','ECONOMIA','BIENESTAR'),
  PUBLICATION_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY(ID)
);